# fly.toml app configuration file
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "tiktok-miner"
primary_region = "sjc"   

[build]
 dockerfile = "Dockerfile"
  
[env]
  # App Configuration
  NEXT_PUBLIC_APP_URL = "https://tiktok-miner.fly.dev"
  NODE_ENV = "production"
  VERCEL_ENV = "production"
  PORT = "8080"
  
  # Default non-sensitive configuration
  OPENAI_MODEL = "gpt-4o"
  OPENAI_TEMPERATURE = "0.7"
  OPENAI_MIN_CONFIDENCE = "0.5"
  GITHUB_TOKEN_LB_STRATEGY = "ROUND_ROBIN"
  LOG_LEVEL = "debug"
  SMTP_PORT = "465"
  SMTP_SECURE = "true"
  SMTP_AUTH_METHOD = "login"
  
  # Retry configuration
  MAX_RETRIES = "3"
  RETRY_DELAY = "1000"
  TIMEOUT_MS = "30000"
  RETRY_ATTEMPTS = "3"
  
  # Rate limit configuration
  RATE_LIMIT_WINDOW = "60000"
  RATE_LIMIT_MAX_REQUESTS = "60"
  
  # Cache configuration
  CACHE_TTL = "3600000"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  memory = "512"
  cpus = 1

[checks]
  [checks.health]
    type = "http"
    grace_period = "30s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/api/health"

# NOTE: Sensitive environment variables should be set using Fly secrets:
# fly secrets set SUPABASE_DATABASE_PASSWORD=your_password
# fly secrets set DATABASE_URL=your_database_url
# fly secrets set DIRECT_URL=your_direct_url
# fly secrets set NEXT_PUBLIC_SUPABASE_URL=your_supabase_url
# fly secrets set NEXT_PUBLIC_SUPABASE_ANON_KEY=your_anon_key
# fly secrets set OPENAI_API_KEY=your_openai_key
# fly secrets set ANTHROPIC_API_KEY=your_anthropic_key
# fly secrets set GITHUB_TOKEN=your_github_token
# fly secrets set GITHUB_TOKENS=token1,token2,token3
# fly secrets set AZURE_EMAIL_CONNECTION_STRING=your_azure_connection
# fly secrets set SMTP_HOST=your_smtp_host
# fly secrets set SMTP_USER=your_smtp_user
# fly secrets set SMTP_PASSWORD=your_smtp_password