codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: true

coverage:
  precision: 2
  round: down
  range: "70...100"
  
  status:
    project:
      default:
        target: 80%
        threshold: 2%
        paths:
          - "lib/"
          - "app/"
          - "components/"
        
    patch:
      default:
        target: 80%
        threshold: 5%

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no
  require_base: no
  require_head: yes

ignore:
  - "**/*.test.ts"
  - "**/*.test.tsx"
  - "**/*.spec.ts"
  - "**/*.spec.tsx"
  - "__tests__/**/*"
  - "e2e/**/*"
  - "coverage/**/*"
  - "dist/**/*"
  - ".next/**/*"
  - "node_modules/**/*"
  - "**/*.d.ts"

flags:
  unittests:
    paths:
      - lib/
      - app/
      - components/
    carryforward: false
    
  integration:
    paths:
      - lib/
      - app/
    carryforward: false
    
  e2e:
    paths:
      - app/
      - components/
    carryforward: false